#
# Global setting
# GIT TEST
###########################################
spring:
  profiles:
    active: local
  application:
    name: tumble-api-bo
  web:
    locale: ko
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
  messages:
    encoding: UTF-8
    use-code-as-default-message: false
    fallback-to-system-locale: true
    basename:
      message.admin.adminCommon

  cache:
    jcache:
      config: classpath:ehcache.xml
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 500MB
  lifecycle:
    timeout-per-shutdown-phase: 10m
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  shutdown: graceful

mybatis:
  type-aliases-package: kr.co.tumble.api.bo.app
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

app:
  lang:
    defaultCntryCd: KR
    defaultSystemLanguage: ko

management:
  health:
    defaults:
      enabled: false
  endpoint:
    health:
      show-details: never
      show-components: never
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

upload:
  s3:
    path: files/


jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 1000
    pool-size: 1
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    string-output-type: base64

crypto:
  secret:
    key: X2BEE_Application_DATA_SecretKey

global:
  response:
    advice: true

site:
  info:
    aop: false


# restapi ??? ??? cookie ??
cookies:
  - site_no
  - lang_cd
  - sessNo


# mail template root path
mail:
  template-root-path: email/apibo

springdoc:
  swagger-ui:
    path: /index.html
    enabled: false
  api-docs:
    path: /api-docs
    enabled: false

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: error

---
#
# LOCAL Setting
###########################################
server:
  port: 8097
  servlet:
    context-path: /api/bo
  max-http-request-header-size: 800000

spring:
  config:
    activate:
      on-profile: local
  mvc:
    log-request-details: true
  zipkin:
    enabled: false
  devtools:
    livereload:
      port: 3${server.port}
    restart:
      exclude: mapper/**
